workflows:
  dia_register_build:
    name: DIA Register Auto Project Detection
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        PROJECT_NAME: "DIA Register"
        FLUTTER_ROOT: "/Users/builder/clone"
    scripts:
      - name: Locate Flutter project
        script: |
          echo "🔍 Searching for pubspec.yaml up to 6 levels deep..."
          FOUND_DIR=$(find . -maxdepth 6 -type f -name "pubspec.yaml" -exec dirname {} \; | head -n 1)
          if [ -z "$FOUND_DIR" ]; then
            echo "❌ No Flutter project found!"
            exit 1
          else
            echo "✅ Flutter project found at: $FOUND_DIR"
            cd "$FOUND_DIR"
          fi
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build Android release APK
        script: |
          flutter build apk --release
          mkdir -p $CM_BUILD_DIR/build_outputs
          cp build/app/outputs/flutter-apk/app-release.apk $CM_BUILD_DIR/build_outputs/DIA_Register_release.apk
      - name: Build iOS release IPA (optional)
        script: |
          if [ -d "ios" ]; then
            echo "🍏 Building iOS IPA..."
            flutter build ios --release --no-codesign
          else
            echo "ℹ️ Skipping iOS build — no ios folder detected."
          fi
    artifacts:
      - build_outputs/*.apk
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com





