workflows:
  dia_register_build:
    name: DIA Register Auto Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Locate Flutter project
        script: |
          echo "🔍 Searching for pubspec.yaml..."
          cd $CM_BUILD_DIR
          PROJECT_DIR=$(find . -maxdepth 3 -type f -name "pubspec.yaml" -exec dirname {} \; | head -n 1)
          echo "📁 Found project at: $PROJECT_DIR"
          if [ -z "$PROJECT_DIR" ]; then
            echo "❌ No Flutter project found!"
            exit 1
          fi
          echo $PROJECT_DIR > /tmp/flutter_project_path.txt

      - name: Repair Flutter structure (safely)
        script: |
          PROJECT_DIR=$(cat /tmp/flutter_project_path.txt)
          cd $CM_BUILD_DIR/$PROJECT_DIR
          echo "🛠️ Running flutter create --overwrite ..."
          flutter create . --overwrite

      - name: Install Flutter dependencies
        script: |
          PROJECT_DIR=$(cat /tmp/flutter_project_path.txt)
          cd $CM_BUILD_DIR/$PROJECT_DIR
          echo "📦 Installing dependencies ..."
          flutter pub get

      - name: Build Android release APK
        script: |
          PROJECT_DIR=$(cat /tmp/flutter_project_path.txt)
          cd $CM_BUILD_DIR/$PROJECT_DIR
          echo "🏗️ Building DIA Register release APK ..."
          flutter build apk --release
          mkdir -p $CM_BUILD_DIR/build_outputs
          cp build/app/outputs/flutter-apk/app-release.apk \
             $CM_BUILD_DIR/build_outputs/DIA_Register_v1.0.apk

    artifacts:
      - build_outputs/**/*.apk

    publishing:
      email:
        recipients:
          - your-email@example.com  # ← replace with your email




