workflows:
  auto_unzip_and_build:
    name: DIA Guest & Members Register (Auto Build for Android + iOS)
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Unzip and locate Flutter project
        script: |
          echo "🔧 Unzipping Flutter project..."
          unzip dia_guest_register_codermagic_ready.zip -d project_root
          echo "✅ Unzip complete. Detecting Flutter project folder..."
          cd project_root
          PROJECT_DIR=$(find . -type f -name "pubspec.yaml" -exec dirname {} \; | head -n 1)
          echo "📂 Found Flutter project directory: $PROJECT_DIR"
          cd "$PROJECT_DIR"
          echo $PROJECT_DIR > /tmp/flutter_project_path.txt
          pwd
          ls -la

      - name: Repair Flutter project structure (fix Gradle)
        script: |
          echo "🧩 Repairing Flutter project structure..."
          PROJECT_DIR=$(cat /tmp/flutter_project_path.txt)
          cd "project_root/$PROJECT_DIR"
          flutter create . --overwrite
          echo "✅ Flutter project structure repaired."

      - name: Install Flutter dependencies
        script: |
          echo "📦 Installing Flutter dependencies..."
          PROJECT_DIR=$(cat /tmp/flutter_project_path.txt)
          cd "project_root/$PROJECT_DIR"
          flutter pub get

      - name: Build Android release APK
        script: |
          echo "🏗️ Building DIA Guest & Members Register release APK..."
          PROJECT_DIR=$(cat /tmp/flutter_project_path.txt)
          cd "project_root/$PROJECT_DIR"
          flutter build apk --release
          echo "📦 Renaming APK..."
          mkdir -p build_outputs
          cp build/app/outputs/flutter-apk/app-release.apk build_outputs/DIA_Guest_Register_v1.0.apk

      - name: Build iOS release IPA
        script: |
          echo "🍏 Building DIA Guest & Members Register release IPA..."
          PROJECT_DIR=$(cat /tmp/flutter_project_path.txt)
          cd "project_root/$PROJECT_DIR"
          cd ios
          pod install --repo-update
          cd ..
          flutter build ipa --release --no-codesign
          echo "📦 Renaming IPA..."
          mkdir -p build_outputs
          cp build/ios/ipa/*.ipa build_outputs/DIA_Guest_Register_v1.0.ipa

    artifacts:
      - project_root/**/build_outputs/DIA_Guest_Register_v1.0.apk
      - project_root/**/build_outputs/DIA_Guest_Register_v1.0.ipa

    publishing:
      email:
        recipients:
          - your_email@example.com

