workflows:
  auto_unzip_and_build:
    name: DIA Guest & Members Register (Auto Build for Android + iOS)
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Unzip Flutter project
        script: |
          echo "🔧 Unzipping Flutter project..."
          unzip dia_guest_register_codermagic_ready.zip -d project_root
          echo "✅ Unzip complete. Detecting Flutter project folder..."
          cd project_root
          PROJECT_DIR=$(find . -type f -name "pubspec.yaml" -exec dirname {} \; | head -n 1)
          echo "📂 Found Flutter project directory: $PROJECT_DIR"
          cd "$PROJECT_DIR"
          pwd
          ls -la

      - name: Install Flutter dependencies
        script: |
          echo "📦 Installing Flutter dependencies..."
          flutter pub get

      - name: Build Android release APK
        script: |
          echo "🏗️ Building DIA Guest & Members Register release APK..."
          flutter build apk --release
          echo "📦 Renaming APK..."
          mkdir -p ../../build_outputs
          cp build/app/outputs/flutter-apk/app-release.apk ../../build_outputs/DIA_Guest_Register_v1.0.apk

      - name: Build iOS release IPA
        script: |
          echo "🍏 Building DIA Guest & Members Register release IPA..."
          cd ios
          pod install --repo-update
          cd ..
          flutter build ipa --release --no-codesign
          echo "📦 Renaming IPA..."
          mkdir -p ../../build_outputs
          cp build/ios/ipa/*.ipa ../../build_outputs/DIA_Guest_Register_v1.0.ipa

    artifacts:
      - build_outputs/DIA_Guest_Register_v1.0.apk
      - build_outputs/DIA_Guest_Register_v1.0.ipa

    publishing:
      email:
        recipients:
          - your_email@example.com
